---
- hosts: webservers
  become: True
  tasks:
    - name: Checkout git branch
      git:
        repo: git@github.com:mehediemon/Task-Managment-Site.git
        dest: /opt/taskApp/
        version: "origin/master"
        key_file: /home/ubuntu/.ssh/git
        accept_hostkey: yes
        force: yes

    - name: Ensure directory has correct permissions.
      file:
        path:  /opt/taskApp/
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu

    - name: Ensure directory has correct permissions.
      file:
        path:  /opt/static/
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
    
    - name: Ensure directory has correct permissions.
      file:
        path:  /opt/media/
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu

    - name: Stop and remove containers defined in Docker Compose file
      command: docker compose -f /opt/taskApp/docker-compose.yml down
      args:
        chdir: /opt/taskApp
      ignore_errors: yes  # Ignore errors in case there are no containers to stop

    - name: Remove all Docker images
      shell:
        cmd: docker rmi -f $(docker images -q)
      ignore_errors: yes  # Ignore errors in case there are no images to remove

    - name: Rebuild Docker Compose services
      command: docker compose -f /opt/taskApp/docker-compose.yml build
      args:
        chdir: /opt/taskApp

    - name: Start Docker Compose services
      command: docker compose -f /opt/taskApp/docker-compose.yml up -d
      args:
        chdir: /opt/taskApp
    
    - name: Start migrations
      shell:
        cmd: docker exec -it task-managment-site-taskmanagmentsite-1 /bin/sh -c "/app/mig.sh"
      ignore_errors: yes  # Ignore errors in case there are no images to remove
        
    - name: Restart Nginx
      shell:
        cmd: systemctl restart nginx.service
