version: '3.4'

services:
  taskmanagmentsite:
    image: taskmanagmentsite
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8001
    volumes:
      - /opt/static:/app/collected_static
      - /opt/media:/app/media
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "TaskManagmentSite.wsgi"]
