# Generated by Django 4.2.5 on 2023-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Completed')], default='0', max_length=1)),
                ('time', models.FloatField()),
            ],
        ),
    ]
