# Generated by Django 4.2.5 on 2023-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
