# Generated by Django 4.2.5 on 2023-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='file',
            field=models.FileField(upload_to='documetns/'),
        ),
    ]
