# Generated by Django 4.2.5 on 2023-10-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_task_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
